### ISSUE TITLE
Support env in template path

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#13]
Let's support environment variables in templates files location:
```yaml
gitstrap:
  templates:
    - name: "README.md"
      location: "$HOME/.gitstrap/README.md"
```
